import { ReactNode } from "react";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { getCssText } from "@/stitches.config";
import { globalStyle } from "@/styles/global";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Bookwise",
    template: "%s | Bookwise",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  globalStyle();
  return (
    <html lang="en">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </head>
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
